export const API_ENDPOINTS = {
  DASHBOARD_STATS: "/dashboard/stats",
  NOTIFICATION: "/notifications",
  CLEAR_ALL_NOTIFICATIONS: "/notifications/clear-all",
  EMAIL: "/send-email",
  SHOP_SETTINGS: "/shop-settings",
  CASH_SALE: "/sales?type=cash",
  SALE: "/sales",
  CUSTOMERS: "/customers",
  PERMANENT: "/customers/permanent",
  CUSTOMERS_SALE: (customerId) => `/customers/${customerId}/sales`,
  CUSTOMER_PAYMENT: (customerId) => `/customers/${customerId}/payment`,
  SALE_BY_ID: (saleId) => `/sales/${saleId}`,
  TEMPORARY_SALES: "/sales?type=temporary",
  CATEGORIES: "/categories",
  UPDATE_CATEGORY: (categoryId) => `/categories/${categoryId}`,
  TOGGLE_CATEGORY: (categoryId) => `/categories/${categoryId}/toggle`,
  DELETE_CATEGORY: (categoryId) => `/categories/${categoryId}`,
  LOCATIONS: "/locations",
  LOCATION_BY_ID: (locationId) => `/locations/${locationId}`,
  TOGGLE_LOCATION: (locationId) => `/locations/${locationId}/toggle`,
  PRODUCTS: "/products",
  PRODUCT_BY_ID: (productId) => `/products/${productId}`,
  EMPLOYEES: "/employees",
  EMPLOYEE_BY_ID: (employeeId) => `/employees/${employeeId}`,
  PAY_SALARY: (employeeId) => `/employees/${employeeId}/pay-salary`,
  SALE_REPORT: "/sales/report",
  SALE_REPORT_SALE: "/reports/sales",

  // Expenses (NEW)
  EXPENSES: "/expenses",
  EXPENSE_BY_ID: (id) => `/expenses/${id}`,
  EXPENSE_SUMMARY: "/expenses/summary",
};
